# Generated by Django 6.0.1 on 2026-01-21 03:05

import base.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Electronic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to=base.models.getFilename
                    ),
                ),
                ("desc", models.CharField(max_length=500)),
                (
                    "status",
                    models.BooleanField(default=False, help_text="0-show,1-Hidden"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Fashtion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to=base.models.getFilename
                    ),
                ),
                ("desc", models.CharField(max_length=500)),
                (
                    "status",
                    models.BooleanField(default=False, help_text="0-show,1-Hidden"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Grocery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to=base.models.getFilename
                    ),
                ),
                ("desc", models.CharField(max_length=500)),
                (
                    "status",
                    models.BooleanField(default=False, help_text="0-show,1-Hidden"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Health",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to=base.models.getFilename
                    ),
                ),
                ("desc", models.CharField(max_length=500)),
                (
                    "status",
                    models.BooleanField(default=False, help_text="0-show,1-Hidden"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Home_Applienc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to=base.models.getFilename
                    ),
                ),
                ("desc", models.CharField(max_length=500)),
                (
                    "status",
                    models.BooleanField(default=False, help_text="0-show,1-Hidden"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="F_Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("vender", models.CharField(max_length=150)),
                (
                    "product_image",
                    models.ImageField(
                        blank=True, null=True, upload_to=base.models.getFilename
                    ),
                ),
                ("quentity", models.IntegerField()),
                ("original_prise", models.IntegerField()),
                ("selling_price", models.IntegerField()),
                ("desc", models.CharField(max_length=500)),
                (
                    "status",
                    models.BooleanField(default=False, help_text="0-show,1-Hidden"),
                ),
                (
                    "trending",
                    models.BooleanField(
                        default=False, help_text="0-default,1-Trending"
                    ),
                ),
                (
                    "catogry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.fashtion"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="G_Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("vender", models.CharField(max_length=150)),
                (
                    "product_image",
                    models.ImageField(
                        blank=True, null=True, upload_to=base.models.getFilename
                    ),
                ),
                ("quentity", models.IntegerField()),
                ("original_prise", models.IntegerField()),
                ("selling_price", models.IntegerField()),
                ("desc", models.CharField(max_length=500)),
                (
                    "status",
                    models.BooleanField(default=False, help_text="0-show,1-Hidden"),
                ),
                (
                    "trending",
                    models.BooleanField(
                        default=False, help_text="0-default,1-Trending"
                    ),
                ),
                (
                    "catogry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.grocery"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="H_Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("vender", models.CharField(max_length=150)),
                (
                    "product_image",
                    models.ImageField(
                        blank=True, null=True, upload_to=base.models.getFilename
                    ),
                ),
                ("quentity", models.IntegerField()),
                ("original_prise", models.IntegerField()),
                ("selling_price", models.IntegerField()),
                ("desc", models.CharField(max_length=500)),
                (
                    "status",
                    models.BooleanField(default=False, help_text="0-show,1-Hidden"),
                ),
                (
                    "trending",
                    models.BooleanField(
                        default=False, help_text="0-default,1-Trending"
                    ),
                ),
                (
                    "catogry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.home_applienc",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HT_Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("vender", models.CharField(max_length=150)),
                (
                    "product_image",
                    models.ImageField(
                        blank=True, null=True, upload_to=base.models.getFilename
                    ),
                ),
                ("quentity", models.IntegerField()),
                ("original_prise", models.IntegerField()),
                ("selling_price", models.IntegerField()),
                ("desc", models.CharField(max_length=500)),
                (
                    "status",
                    models.BooleanField(default=False, help_text="0-show,1-Hidden"),
                ),
                (
                    "trending",
                    models.BooleanField(
                        default=False, help_text="0-default,1-Trending"
                    ),
                ),
                (
                    "catogry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.health"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("vender", models.CharField(max_length=150)),
                (
                    "product_image",
                    models.ImageField(
                        blank=True, null=True, upload_to=base.models.getFilename
                    ),
                ),
                ("quentity", models.IntegerField()),
                ("original_prise", models.IntegerField()),
                ("selling_price", models.IntegerField()),
                ("desc", models.CharField(max_length=500)),
                (
                    "status",
                    models.BooleanField(default=False, help_text="0-show,1-Hidden"),
                ),
                (
                    "trending",
                    models.BooleanField(
                        default=False, help_text="0-default,1-Trending"
                    ),
                ),
                (
                    "catogry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.electronic",
                    ),
                ),
            ],
        ),
    ]
