# Generated by Django 5.2.7 on 2026-02-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="g_product",
            name="catogry",
        ),
        migrations.RemoveField(
            model_name="h_product",
            name="catogry",
        ),
        migrations.RemoveField(
            model_name="ht_product",
            name="catogry",
        ),
        migrations.AlterField(
            model_name="electronic",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.DeleteModel(
            name="F_Product",
        ),
        migrations.DeleteModel(
            name="Fashtion",
        ),
        migrations.DeleteModel(
            name="G_Product",
        ),
        migrations.DeleteModel(
            name="Grocery",
        ),
        migrations.DeleteModel(
            name="H_Product",
        ),
        migrations.DeleteModel(
            name="Home_Applienc",
        ),
        migrations.DeleteModel(
            name="Health",
        ),
        migrations.DeleteModel(
            name="HT_Product",
        ),
    ]
