# Generated by Django 5.2.7 on 2026-02-03 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_remove_g_product_catogry_remove_h_product_catogry_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="original_prise",
            new_name="original_price",
        ),
    ]
