# Generated by Django 5.2.7 on 2026-02-11 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_cart"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="quentity",
            new_name="quantity",
        ),
    ]
