# Generated by Django 5.2.7 on 2026-02-11 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_rename_quentity_product_quantity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="quantity",
            new_name="quentity",
        ),
    ]
