# Generated by Django 5.2.7 on 2026-02-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_ard_delete_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ard",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="ard",
            name="product_qty",
            field=models.IntegerField(),
        ),
    ]
